Create Contributing.md
mj1856/SqlServerTimeZoneSupport pull request #35
Opened 2018-06-27 22:38 UTC by martincheck

I'm submitting this pull request more for feedback than expecting this to be done.  I need to get the formatting a little cleaned up, and have a few TBA sections.  Feel free to bounce back with feedback, or fill in the blanks, or remove the TBA's and post as is (i.e. good enough and we'll iterate)

2018-06-27 23:48 UTC, mj1856 commented
Thanks for getting this started!  Let's keep this here in pull-request form for the time being.  We can continue to discuss and you can simply push additional commits to your branch for them to show up here.

Perhaps start with adding URLs where appropriate?  That would help. 😄

2018-07-06 03:05 UTC, maggiepint requested changes
This is in pretty good shape. Clean up these couple things and I'll merge it

2018-07-06 03:05 UTC, maggiepint commented on Contributing.md
> +<to be added - some blurb about
Typically, @mj1856 uses the up-for-grabs tag to indicate beginner issues.

2018-07-06 03:05 UTC, maggiepint commented on Contributing.md
> +For something that is bigger than a one or two line fix:
In this project we would probably fork for everything.

2018-07-06 03:05 UTC, maggiepint commented on Contributing.md
> +Explain how a contribution gets accepted after it’s been submitted.
Let's remove the boilerplate here.

2018-07-06 03:05 UTC, maggiepint commented on Contributing.md
> +The core team (basically Matt) looks at Pull Requests on a best effort basis. We seek to get better, and are looking for volunteers to co-maintain the library to increase the cadence.
This is pretty accurate

2018-07-06 03:05 UTC, maggiepint commented on Contributing.md
> +## Ground Rules
Let's either remove this, or replace it with a link to a code of conduct like [Contributor covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.md)

2018-07-06 03:05 UTC, maggiepint commented on Contributing.md
> +Unsure where to begin contributing? You can start by looking through these beginner and help-wanted issues:
I would simplify this to "Unsure where to begin contribution? Look for issues with an up-for-grabs or help-wanted tag"

2018-07-06 17:24 UTC, martincheck commented on Contributing.md
> +## Ground Rules
any preference regrading whether I copy and paste this inline, or link to it?  I'll start with linking and see how that works...

2018-07-06 19:40 UTC, maggiepint approved these changes

2018-07-06 19:40 UTC, merged